# Generated by Django 5.1.3 on 2024-11-20 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=1000)),
                ('is_completed', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('estimated_time', models.TimeField()),
                ('category', models.CharField(choices=[('Compulsary', 'Compulsary'), ('Optional', 'Optional')], max_length=20)),
                ('DayPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.dayplan')),
            ],
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
