# Generated by Django 5.1.3 on 2024-11-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_dayplan_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='completed_compulsary_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='completed_optional_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='total_compulsary_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='total_optional_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='info',
            name='last_active_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='total_active_days',
            field=models.IntegerField(default=0),
        ),
    ]
