# Generated by Django 5.1.3 on 2024-11-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_dayplan_completed_compulsary_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayplan',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='info',
            name='discipline_score',
            field=models.FloatField(default=0),
        ),
    ]
